const {test}=require('node:test');const assert=require('node:assert/strict');
const {getSelfConfirmations,putSelfConfirmation,validatePair}=require('./lesson-visit-self-confirmations');
function db(global=true) {const calls=[];return {calls,async query(sql,args){calls.push({sql,args});if(sql.includes('FROM lesson_visit_projects'))return {rows:[{id:3,state_json:{directory:{teachers:[{id:'a',name:'Учитель'}]},pulse_self_confirmations:{7:{selfId:7,lessonId:8}}}}]};if(sql.includes('FROM pulse_visit_report_grants'))return {rows:global ? [{lesson_id:null,department_id:null}]:[{lesson_id:null,department_id:'d'}]};if(sql.includes('FROM lesson_visit_responses'))return {rows:[{id:1,answers_json:{general:{teacher_id:'a',visit_format:'Самоанализ'}}},{id:2,answers_json:{general:{teacher_id:'a',visit_format:'Наблюдение'}}}]};if(sql.startsWith('UPDATE'))return {rows:[{state_json:{pulse_self_confirmations:{7:{selfId:7,lessonId:8},1:JSON.parse(args[2])}}}]};throw Error(sql);}};}
const actor={id:12};
test('read is protected by the existing global grant and never writes',async()=>{const pool=db();const r=await getSelfConfirmations(pool,actor,null,3);assert.equal(r.statusCode,200);assert.equal(JSON.parse(r.body).confirmations.length,1);assert.ok(pool.calls.every(c=>!c.sql.startsWith('UPDATE')));const denied=await getSelfConfirmations(db(false),actor,null,3);assert.equal(denied.statusCode,403);assert.equal((await getSelfConfirmations(db(),null,null,3)).statusCode,403);});
test('only pair metadata is patched, preserving source records and previous confirmations',async()=>{const pool=db();const r=await putSelfConfirmation(pool,actor,null,3,{body:JSON.stringify({selfId:1,lessonId:2})});assert.equal(r.statusCode,200);const data=JSON.parse(r.body);assert.equal(data.confirmations.length,2);const writes=pool.calls.filter(c=>c.sql.startsWith('UPDATE'));assert.equal(writes.length,1);assert.match(writes[0].sql,/jsonb_set.*pulse_self_confirmations/s);assert.doesNotMatch(writes[0].sql,/lesson_visit_responses|UPDATE users|updated_at/);});
test('teacher mismatch and invalid IDs reject the request without mutations',async()=>{assert.match(validatePair([{id:1,answers_json:{general:{teacher_name:'A',format:'Самоанализ'}}},{id:2,answers_json:{general:{teacher_name:'B',format:'Наблюдение'}}}],1,2,{}),/разным учителям/);const pool=db();assert.equal((await putSelfConfirmation(pool,actor,null,3,{body:JSON.stringify({selfId:1,lessonId:1})})).statusCode,400);assert.ok(pool.calls.every(c=>!c.sql.startsWith('UPDATE')));});
test('legacy name allowlist alone cannot enable confirmation; existing platform owner can inspect it',async()=>{
 const denied=await getSelfConfirmations(db(false),{id:99,email:'marianna.primakova@primakov.school',display_name:'Примакова Марианна Николаевна'},null,3);assert.equal(denied.statusCode,403);
 const previous=process.env.PULSE_PLATFORM_OWNER_USER_ID;process.env.PULSE_PLATFORM_OWNER_USER_ID='27';
 try{assert.equal((await getSelfConfirmations(db(false),{id:27},null,3)).statusCode,200);}finally{previous==null?delete process.env.PULSE_PLATFORM_OWNER_USER_ID:process.env.PULSE_PLATFORM_OWNER_USER_ID=previous;}
});
