import {useState} from 'react';
import {sourceRequest,type SourceRecord,type DepartmentAssignments} from '../../api/visitChecklistV3';
export default function AssessmentSourceSetup({data,onChange}:{data:DepartmentAssignments;onChange:()=>void}){
 const [records,setRecords]=useState<SourceRecord[]>([]),[lesson,setLesson]=useState(''),[author,setAuthor]=useState(''),[selected,setSelected]=useState(''),[link,setLink]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 const current=records.find(r=>r.checklist.checklist_id===selected);
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');setNote('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Ошибка обработки');}finally{setBusy(false);}}
 async function load(){const response=await sourceRequest<{records:SourceRecord[]}>(data.project_id,'assessments');setRecords(response.records);}
 return <section><h3>Сверка исходных чек-листов и подготовка наблюдений</h3><p>Связи выбираются по стабильным ID. Имена и даты старых ответов не служат автоматическим подтверждением. Расчёт запускается только отдельным действием.</p>
 {error&&<p role="alert">{error}</p>}{note&&<p role="status">{note}</p>}
 <button disabled={busy} onClick={()=>void perform(load)}>Открыть сохранённые редакции</button><button disabled={busy} onClick={()=>void perform(async()=>{await sourceRequest(data.project_id,'backfill',{});await load();setNote('Источники сохранены без вызова ИИ. Проверьте неподвязанные записи.');})}>Подготовить старые источники к сверке</button>
 <div className="pv3-filters"><label>Проверенный урок<select value={lesson} onChange={e=>{setLesson(e.target.value);setLink('');}}><option value="">Выберите урок</option>{data.lessons.map(l=><option key={l.lesson_id} value={l.lesson_id}>{l.metadata.date} · {l.metadata.class_name} · {l.metadata.subject} · {l.lesson_id}</option>)}</select></label><label>Автор чек-листа<select value={author} onChange={e=>{setAuthor(e.target.value);setLink('');}}><option value="">Выберите пользователя</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.label}</option>)}</select></label><label>Существующий чек-лист<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите редакцию</option>{records.map(r=><option key={r.checklist.checklist_id} value={r.checklist.checklist_id}>{r.checklist.checklist_id} · редакция {r.checklist.revision} · {r.checklist.lesson_id||'Неподвязан'}</option>)}</select></label></div>
 {current&&<details><summary>Исходные ответы выбранной редакции</summary>{Object.entries(current.checklist.answers).map(([code,a])=><p key={code}>{code}: {a.selected_options.map(o=>o.label).join('; ')} {a.text}</p>)}</details>}
 <button disabled={busy||!current||!lesson||!author} onClick={()=>void perform(async()=>{if(!current)return;await sourceRequest(data.project_id,`checklists/${encodeURIComponent(current.checklist.checklist_id)}`,{expected_revision:current.checklist.revision,answers:current.checklist.answers,lesson_id:lesson,author_id:author},'PATCH');await load();setNote('Создана новая редакция с проверенной связью. Исходная редакция сохранена в истории.');onChange();})}>Сохранить подтверждённую привязку</button>
 <button disabled={busy||!current} onClick={()=>void perform(async()=>{if(!current)return;const r=await sourceRequest<{status:string}>(data.project_id,`calculate/${encodeURIComponent(current.checklist.checklist_id)}`,{});await load();setNote(`Статус расчёта: ${r.status}`);onChange();})}>Оценить выбранную редакцию</button>
 <button disabled={busy||!lesson||!author} onClick={()=>void perform(async()=>{const context=await sourceRequest<{pulse_context:string}>(data.project_id,'submission-contexts',{lesson_id:lesson,author_id:author});setLink(`/cabinet/feedback/form?token=${encodeURIComponent(data.form_token)}&pulse_context=${encodeURIComponent(context.pulse_context)}`);setNote('Одноразовая ссылка на 7 дней закрепляет ID урока и автора.');})}>Подготовить новое наблюдение</button>{link&&<p><a href={link}>Открыть чек-лист для выбранного урока и автора</a></p>}
 {busy&&<p role="status">Выполняем выбранное действие…</p>}
 </section>;
}
