import {useState} from 'react';
import {patchDepartmentAssignment,type InterfaceSettings} from '../../api/visitChecklistV3';
const groups=['screens','navigation','teacher_tabs','sections','filters','metrics','blocks','scored_criteria','descriptive_criteria','exports','new_manager_actions'] as const;
const groupTitles=['Экраны','Навигация','Вкладки учителя','Разделы','Фильтры','Показатели','Блоки','Критерии с баллами','Описательные пункты','Excel','Отправка отчёта'];
const optional={weekly_comparison:'Еженедельная сводка',report_queue:'Очередь отчётов',block_results:'Таблица блоков',priorities:'Приоритеты методической работы',risk:'Группа риска',version_details:'Версия расчёта'};
export default function InterfaceSettingsEditor({projectId,settings,onChange}:{projectId:number;settings:InterfaceSettings;onChange:()=>void}){
 const [group,setGroup]=useState<typeof groups[number]>('screens');
 const [labels,setLabels]=useState<Record<string,Record<string,string>>>(()=>Object.fromEntries(groups.map(g=>[g,{...settings.names[g]}])));
 const [hidden,setHidden]=useState(settings.hidden),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(restore_revision?:number){setBusy(true);setError('');try{await patchDepartmentAssignment(projectId,{action:restore_revision==null?'save_interface':'restore_interface',revision:settings.revision,labels,hidden,restore_revision});onChange();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить настройки');}finally{setBusy(false);}}
 return <details><summary>Настройки интерфейса</summary><p>Версия {settings.revision}. Формулировки меняются на экране и в новых выгрузках. Баллы и исходные ответы сохраняются.</p><label>Что редактировать<select value={group} onChange={e=>setGroup(e.target.value as typeof group)}>{groups.map((g,i)=><option key={g} value={g}>{groupTitles[i]}</option>)}</select></label><div className="pv3-tablewrap"><table><thead><tr><th>Действующая формулировка</th><th>Новая формулировка</th><th>Предпросмотр</th></tr></thead><tbody>{Object.entries(settings.names[group]).map(([id,text])=><tr key={group+id}><td>{text}</td><td><input aria-label={text} value={labels[group][id]} maxLength={1000} onChange={e=>setLabels(v=>({...v,[group]:{...v[group],[id]:e.target.value}}))}/></td><td>{labels[group][id]}</td></tr>)}</tbody></table></div><fieldset><legend>Необязательные блоки</legend>{Object.entries(optional).map(([id,title])=><label key={id}><input type="checkbox" checked={!hidden.includes(id)} onChange={e=>setHidden(v=>e.target.checked?v.filter(x=>x!==id):[...v,id])}/>{title}</label>)}</fieldset><button disabled={busy} onClick={()=>void save()}>Сохранить</button>{error&&<p role="alert">{error}</p>}<details><summary>История и восстановление</summary>{settings.history.length?settings.history.slice().reverse().map(h=><p key={h.revision}>Версия {h.revision} · {new Date(h.changed_at).toLocaleString('ru-RU')} · автор {h.actor_id} <button disabled={busy} onClick={()=>void save(h.revision)}>Восстановить</button></p>):<p>История пока пуста.</p>}</details></details>;
}
